Remove direct dependency to `en-navigation-api`.
electrode-io/ern-navigation pull request #15
Opened 2019-12-02 23:08 UTC by deepueg

This has to be transitive dependency inside the `ernnavigation-api-impl-native`.

AN update to the API should always be controlled by the implementation to avoid the introduction of any breaking change.
https://github.com/electrode-io/ernnavigation-api-impl-native/blob/master/package.json#L6

2019-12-02 23:34 UTC, friederbluemle approved these changes
👍

2019-12-02 23:35 UTC, friederbluemle commented
Minor: Git commit message subject line should _not_ end with a period. Also try to avoid backticks in the commit message - they don't render on console ;)

2019-12-02 23:36 UTC, friederbluemle requested changes
Please also run `yarn` after modifying `package.json` and add the changes to `yarn.lock` to the same commit.

Edit: At the same time please reword the message: The dependency in question is `ernnavigation-api`, not `en-navigation-api`

2019-12-02 23:44 UTC, friederbluemle commented
Also, quick question (it's still a bit unclear to me what the desired dependency structure between these projects is supposed to look like)..

I see the following line in `src/components/navigation-component.js`:

```
import {EnNavigationApi} from 'ernnavigation-api';
```

That's a _direct_ dependency on `ernnavigation-api` (not `ernnavigation-api-impl-native`) - Of course, in this particular case, it would still work because of the transitive dependency you mentioned. However, this is not a general rule we can assume, and if at some point in the future someone removes/changes a dependency in `ernnavigation-api-impl-native`, it would break consumer projects with no control.

Should this be moved to `peerDependencies` maybe?

2019-12-12 03:17 UTC, deepueg commented
@friederbluemle Valid point. Let's discuss this more in detail.

2019-12-13 19:06 UTC, deepueg commented
Closing this PR. Per our internal discussion, we will continue to keep both dependencies inside `ern-navigation` as the source of truth for what version of these packages are used during container generation for RN, iOS, and Android.

2019-12-13 19:06 UTC, closed without merging